const Consts = {
  APP_WIDTH: 1080,
  APP_HEIGHT: 1080,
  MAX_BOX_SIZE: 160,
  PRIME_NUMBER_COLOR: 0x66CCFF,
  DEFAULT_NUMBER_COLOR: 0xCCCCCC,
  COMPOSITE_NUMBER_COLOR: 0xFFCC55,
}

export default Consts
